name: PR closure
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  delete_preview_app:
    name: Delete preview app
    runs-on: ubuntu-latest
    concurrency:
      group: pr-${{ github.event.number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Delete preview app
        uses: optimumBA/fly-preview-apps@main
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          REPO_NAME: invoice-app
        with:
          name: bill-bliss-pr-${{ github.event.number }}
      - name: Generate token
        uses: navikt/github-app-token-generator@v1.1.1
        id: generate_token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Delete GitHub environment
        uses: strumwolf/delete-deployment-environment@v2.2.3
        with:
          token: ${{ steps.generate_token.outputs.token  }}
          environment: pr-${{ github.event.number }}
          ref: ${{ github.head_ref }}
